//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grapesoft.Petstar.Events
{
    using System;
    using System.Collections.Generic;
    
    public partial class cmsNoticias
    {
        public int id { get; set; }
        public int IdUmbraco { get; set; }
        public Nullable<int> IdParent { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Titulo { get; set; }
        public string Informacion { get; set; }
        public string Link { get; set; }
        public string TextoFecha { get; set; }
        public string Imagen { get; set; }
        public bool Active { get; set; }
        public string Resumen { get; set; }
    }
}
