//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grapesoft.Petstar.Events
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PetstarEntities : DbContext
    {
        public PetstarEntities()
            : base("name=PetstarEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cmsNoticias> cmsNoticias { get; set; }
        public virtual DbSet<cmsLogError> cmsLogError { get; set; }
        public virtual DbSet<cmsMedia> cmsMedia { get; set; }
    
        public virtual ObjectResult<sp_NewsPagination_Result> sp_NewsPagination(Nullable<int> page, Nullable<int> size, Nullable<int> parent, string sort, string param, Nullable<System.DateTime> dateI, Nullable<System.DateTime> dateF, Nullable<bool> filterDate, ObjectParameter totalrow)
        {
            var pageParameter = page.HasValue ?
                new ObjectParameter("page", page) :
                new ObjectParameter("page", typeof(int));
    
            var sizeParameter = size.HasValue ?
                new ObjectParameter("size", size) :
                new ObjectParameter("size", typeof(int));
    
            var parentParameter = parent.HasValue ?
                new ObjectParameter("parent", parent) :
                new ObjectParameter("parent", typeof(int));
    
            var sortParameter = sort != null ?
                new ObjectParameter("sort", sort) :
                new ObjectParameter("sort", typeof(string));
    
            var paramParameter = param != null ?
                new ObjectParameter("param", param) :
                new ObjectParameter("param", typeof(string));
    
            var dateIParameter = dateI.HasValue ?
                new ObjectParameter("dateI", dateI) :
                new ObjectParameter("dateI", typeof(System.DateTime));
    
            var dateFParameter = dateF.HasValue ?
                new ObjectParameter("dateF", dateF) :
                new ObjectParameter("dateF", typeof(System.DateTime));
    
            var filterDateParameter = filterDate.HasValue ?
                new ObjectParameter("filterDate", filterDate) :
                new ObjectParameter("filterDate", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_NewsPagination_Result>("sp_NewsPagination", pageParameter, sizeParameter, parentParameter, sortParameter, paramParameter, dateIParameter, dateFParameter, filterDateParameter, totalrow);
        }
    }
}
